name: dart_pg
description:  Dart PG (Dart Privacy Guard) - The OpenPGP implementation in Dart language.
version: 1.4.0
homepage: https://github.com/web-of-trust/dart-pg

environment:
  sdk: ^3.2.0

dependencies:
  fixnum: ^1.1.0
  pinenacl: ^0.6.0
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^2.0.0
  faker: ^2.0.0
  test: ^1.16.0

false_secrets:
 - /test/data/key_data.dart
 - /test/data/s2k_data.dart
 