name: dart_pg
description:  Dart PG (Dart Privacy Guard) - The OpenPGP implementation in Dart language.
version: 1.1.4
homepage: https://github.com/nguyennv/dart_pg

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  fixnum: ^1.1.0
  pinenacl: ^0.5.1
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^2.0.0
  faker: ^2.0.0
  test: ^1.16.0

false_secrets:
 - /test/data/key_data.dart
 - /test/data/s2k_data.dart
 